// Automatically generated from the message definition "nav_msgs/GetMapActionGoal.msg"
package nav_msgs

import (
	"bytes"
	"ee631_midterm/msgs/actionlib_msgs"
	"ee631_midterm/msgs/std_msgs"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgGetMapActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionGoal) Text() string {
	return t.text
}

func (t *_MsgGetMapActionGoal) Name() string {
	return t.name
}

func (t *_MsgGetMapActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionGoal) NewMessage() ros.Message {
	m := new(GetMapActionGoal)
	m.Header = std_msgs.Header{}
	m.GoalId = actionlib_msgs.GoalID{}
	m.Goal = GetMapGoal{}
	return m
}

var (
	MsgGetMapActionGoal = &_MsgGetMapActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
GetMapGoal goal
`,
		"nav_msgs/GetMapActionGoal",
		"4b30be6cd12b9e72826df56b481f40e0",
	}
)

type GetMapActionGoal struct {
	Header std_msgs.Header       `rosmsg:"header:Header"`
	GoalId actionlib_msgs.GoalID `rosmsg:"goal_id:GoalID"`
	Goal   GetMapGoal            `rosmsg:"goal:GetMapGoal"`
}

func (m *GetMapActionGoal) GetType() ros.MessageType {
	return MsgGetMapActionGoal
}

func (m *GetMapActionGoal) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}
	if err = m.GoalId.Serialize(buf); err != nil {
		return err
	}
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *GetMapActionGoal) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}
	if err = m.GoalId.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}
	return err
}
