// Automatically generated from the message definition "nav_msgs/GetMapAction.msg"
package nav_msgs

import (
	"bytes"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgGetMapAction struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapAction) Text() string {
	return t.text
}

func (t *_MsgGetMapAction) Name() string {
	return t.name
}

func (t *_MsgGetMapAction) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapAction) NewMessage() ros.Message {
	m := new(GetMapAction)
	m.ActionGoal = GetMapActionGoal{}
	m.ActionResult = GetMapActionResult{}
	m.ActionFeedback = GetMapActionFeedback{}
	return m
}

var (
	MsgGetMapAction = &_MsgGetMapAction{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

GetMapActionGoal action_goal
GetMapActionResult action_result
GetMapActionFeedback action_feedback
`,
		"nav_msgs/GetMapAction",
		"e611ad23fbf237c031b7536416dc7cd7",
	}
)

type GetMapAction struct {
	ActionGoal     GetMapActionGoal     `rosmsg:"action_goal:GetMapActionGoal"`
	ActionResult   GetMapActionResult   `rosmsg:"action_result:GetMapActionResult"`
	ActionFeedback GetMapActionFeedback `rosmsg:"action_feedback:GetMapActionFeedback"`
}

func (m *GetMapAction) GetType() ros.MessageType {
	return MsgGetMapAction
}

func (m *GetMapAction) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.ActionGoal.Serialize(buf); err != nil {
		return err
	}
	if err = m.ActionResult.Serialize(buf); err != nil {
		return err
	}
	if err = m.ActionFeedback.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *GetMapAction) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.ActionGoal.Deserialize(buf); err != nil {
		return err
	}
	if err = m.ActionResult.Deserialize(buf); err != nil {
		return err
	}
	if err = m.ActionFeedback.Deserialize(buf); err != nil {
		return err
	}
	return err
}
