// Automatically generated from the message definition "nav_msgs/GetMapGoal.msg"
package nav_msgs

import (
	"bytes"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgGetMapGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapGoal) Text() string {
	return t.text
}

func (t *_MsgGetMapGoal) Name() string {
	return t.name
}

func (t *_MsgGetMapGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapGoal) NewMessage() ros.Message {
	m := new(GetMapGoal)
	return m
}

var (
	MsgGetMapGoal = &_MsgGetMapGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Get the map as a nav_msgs/OccupancyGrid
`,
		"nav_msgs/GetMapGoal",
		"d41d8cd98f00b204e9800998ecf8427e",
	}
)

type GetMapGoal struct {
}

func (m *GetMapGoal) GetType() ros.MessageType {
	return MsgGetMapGoal
}

func (m *GetMapGoal) Serialize(buf *bytes.Buffer) error {
	var err error
	return err
}

func (m *GetMapGoal) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	return err
}
