// Automatically generated from the message definition "nav_msgs/GetMapFeedback.msg"
package nav_msgs

import (
	"bytes"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgGetMapFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapFeedback) Text() string {
	return t.text
}

func (t *_MsgGetMapFeedback) Name() string {
	return t.name
}

func (t *_MsgGetMapFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapFeedback) NewMessage() ros.Message {
	m := new(GetMapFeedback)
	return m
}

var (
	MsgGetMapFeedback = &_MsgGetMapFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# no feedback
`,
		"nav_msgs/GetMapFeedback",
		"d41d8cd98f00b204e9800998ecf8427e",
	}
)

type GetMapFeedback struct {
}

func (m *GetMapFeedback) GetType() ros.MessageType {
	return MsgGetMapFeedback
}

func (m *GetMapFeedback) Serialize(buf *bytes.Buffer) error {
	var err error
	return err
}

func (m *GetMapFeedback) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	return err
}
