// Automatically generated from the message definition "nav_msgs/GetMapActionResult.msg"
package nav_msgs

import (
	"bytes"
	"ee631_midterm/msgs/actionlib_msgs"
	"ee631_midterm/msgs/std_msgs"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgGetMapActionResult struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgGetMapActionResult) Text() string {
	return t.text
}

func (t *_MsgGetMapActionResult) Name() string {
	return t.name
}

func (t *_MsgGetMapActionResult) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgGetMapActionResult) NewMessage() ros.Message {
	m := new(GetMapActionResult)
	m.Header = std_msgs.Header{}
	m.Status = actionlib_msgs.GoalStatus{}
	m.Result = GetMapResult{}
	return m
}

var (
	MsgGetMapActionResult = &_MsgGetMapActionResult{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
GetMapResult result
`,
		"nav_msgs/GetMapActionResult",
		"ac66e5b9a79bb4bbd33dab245236c892",
	}
)

type GetMapActionResult struct {
	Header std_msgs.Header           `rosmsg:"header:Header"`
	Status actionlib_msgs.GoalStatus `rosmsg:"status:GoalStatus"`
	Result GetMapResult              `rosmsg:"result:GetMapResult"`
}

func (m *GetMapActionResult) GetType() ros.MessageType {
	return MsgGetMapActionResult
}

func (m *GetMapActionResult) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}
	if err = m.Result.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *GetMapActionResult) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Result.Deserialize(buf); err != nil {
		return err
	}
	return err
}
