// Automatically generated from the message definition "tf2_msgs/LookupTransformActionGoal.msg"
package tf2_msgs

import (
	"bytes"
	"ee631_midterm/msgs/actionlib_msgs"
	"ee631_midterm/msgs/std_msgs"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgLookupTransformActionGoal struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionGoal) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionGoal) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionGoal) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionGoal) NewMessage() ros.Message {
	m := new(LookupTransformActionGoal)
	m.Header = std_msgs.Header{}
	m.GoalId = actionlib_msgs.GoalID{}
	m.Goal = LookupTransformGoal{}
	return m
}

var (
	MsgLookupTransformActionGoal = &_MsgLookupTransformActionGoal{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
LookupTransformGoal goal
`,
		"tf2_msgs/LookupTransformActionGoal",
		"f2e7bcdb75c847978d0351a13e699da5",
	}
)

type LookupTransformActionGoal struct {
	Header std_msgs.Header       `rosmsg:"header:Header"`
	GoalId actionlib_msgs.GoalID `rosmsg:"goal_id:GoalID"`
	Goal   LookupTransformGoal   `rosmsg:"goal:LookupTransformGoal"`
}

func (m *LookupTransformActionGoal) GetType() ros.MessageType {
	return MsgLookupTransformActionGoal
}

func (m *LookupTransformActionGoal) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}
	if err = m.GoalId.Serialize(buf); err != nil {
		return err
	}
	if err = m.Goal.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *LookupTransformActionGoal) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}
	if err = m.GoalId.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Goal.Deserialize(buf); err != nil {
		return err
	}
	return err
}
