// Automatically generated from the message definition "tf2_msgs/LookupTransformActionFeedback.msg"
package tf2_msgs

import (
	"bytes"
	"ee631_midterm/msgs/actionlib_msgs"
	"ee631_midterm/msgs/std_msgs"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgLookupTransformActionFeedback struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformActionFeedback) Text() string {
	return t.text
}

func (t *_MsgLookupTransformActionFeedback) Name() string {
	return t.name
}

func (t *_MsgLookupTransformActionFeedback) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformActionFeedback) NewMessage() ros.Message {
	m := new(LookupTransformActionFeedback)
	m.Header = std_msgs.Header{}
	m.Status = actionlib_msgs.GoalStatus{}
	m.Feedback = LookupTransformFeedback{}
	return m
}

var (
	MsgLookupTransformActionFeedback = &_MsgLookupTransformActionFeedback{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalStatus status
LookupTransformFeedback feedback
`,
		"tf2_msgs/LookupTransformActionFeedback",
		"aae20e09065c3809e8a8e87c4c8953fd",
	}
)

type LookupTransformActionFeedback struct {
	Header   std_msgs.Header           `rosmsg:"header:Header"`
	Status   actionlib_msgs.GoalStatus `rosmsg:"status:GoalStatus"`
	Feedback LookupTransformFeedback   `rosmsg:"feedback:LookupTransformFeedback"`
}

func (m *LookupTransformActionFeedback) GetType() ros.MessageType {
	return MsgLookupTransformActionFeedback
}

func (m *LookupTransformActionFeedback) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.Header.Serialize(buf); err != nil {
		return err
	}
	if err = m.Status.Serialize(buf); err != nil {
		return err
	}
	if err = m.Feedback.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *LookupTransformActionFeedback) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.Header.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Status.Deserialize(buf); err != nil {
		return err
	}
	if err = m.Feedback.Deserialize(buf); err != nil {
		return err
	}
	return err
}
