// Automatically generated from the message definition "tf2_msgs/LookupTransformAction.msg"
package tf2_msgs

import (
	"bytes"

	"github.com/fetchrobotics/rosgo/ros"
)

type _MsgLookupTransformAction struct {
	text   string
	name   string
	md5sum string
}

func (t *_MsgLookupTransformAction) Text() string {
	return t.text
}

func (t *_MsgLookupTransformAction) Name() string {
	return t.name
}

func (t *_MsgLookupTransformAction) MD5Sum() string {
	return t.md5sum
}

func (t *_MsgLookupTransformAction) NewMessage() ros.Message {
	m := new(LookupTransformAction)
	m.ActionGoal = LookupTransformActionGoal{}
	m.ActionResult = LookupTransformActionResult{}
	m.ActionFeedback = LookupTransformActionFeedback{}
	return m
}

var (
	MsgLookupTransformAction = &_MsgLookupTransformAction{
		`# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

LookupTransformActionGoal action_goal
LookupTransformActionResult action_result
LookupTransformActionFeedback action_feedback
`,
		"tf2_msgs/LookupTransformAction",
		"7ee01ba91a56c2245c610992dbaa3c37",
	}
)

type LookupTransformAction struct {
	ActionGoal     LookupTransformActionGoal     `rosmsg:"action_goal:LookupTransformActionGoal"`
	ActionResult   LookupTransformActionResult   `rosmsg:"action_result:LookupTransformActionResult"`
	ActionFeedback LookupTransformActionFeedback `rosmsg:"action_feedback:LookupTransformActionFeedback"`
}

func (m *LookupTransformAction) GetType() ros.MessageType {
	return MsgLookupTransformAction
}

func (m *LookupTransformAction) Serialize(buf *bytes.Buffer) error {
	var err error
	if err = m.ActionGoal.Serialize(buf); err != nil {
		return err
	}
	if err = m.ActionResult.Serialize(buf); err != nil {
		return err
	}
	if err = m.ActionFeedback.Serialize(buf); err != nil {
		return err
	}
	return err
}

func (m *LookupTransformAction) Deserialize(buf *bytes.Reader) error {
	var err error = nil
	if err = m.ActionGoal.Deserialize(buf); err != nil {
		return err
	}
	if err = m.ActionResult.Deserialize(buf); err != nil {
		return err
	}
	if err = m.ActionFeedback.Deserialize(buf); err != nil {
		return err
	}
	return err
}
